kind: pipeline
type: docker
name: build

steps:
- name: cooked
  image: najahi/oven:latest
  environment:
    BOT_API_KEY:
      from_secret: BOT_API_KEY
    DRONE_SERVER:
      from_secret: DRONE_SERVER
    DRONE_TOKEN:
      from_secret: DRONE_TOKEN
      export DRONE_SERVER=https://cloud.drone.io
      export DRONE_TOKEN=E6H3GSg0Qn0lDQcLPGdLJQZIOcymrNcx
      drone info

  commands:
  - apt update
  - apt install -y libssl-dev
  - wget https://raw.githubusercontent.com/skyhuppa/Script/main/infinix_ci.sh
  - bash infinix_ci.sh land
  
